name: Build DBML docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'dbml-homepage/**'
      - 'dbml-playground/**'

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: dbml-homepage

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          # cache: yarn
          # cache-dependency-path: ./dbml-homepage/yarn.lock

      - name: Check env
        run: |
          node -v
          yarn -v

      - name: Install playground dependencies
        working-directory: dbml-playground
        run: yarn install --frozen-lockfile

      - name: Build playground
        working-directory: dbml-playground
        run: yarn build

      - name: Clean up old playground build
        run: rm -rf static/playground

      - name: Copy playground to homepage static
        run: cp -r ../dbml-playground/dist static/playground

      - name: Check playground
        run: |
          ls -la static/playground

      - name: Install homepage dependencies
        run: yarn install --frozen-lockfile

      - name: Build homepage
        run: yarn build
