name: Deploy DBML docs to Github Pages

on: workflow_dispatch

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies (root)
        run: yarn install --frozen-lockfile

      - name: Build playground
        run: yarn workspace @dbml/playground build

      - name: Clean up old playground build
        run: rm -rf dbml-homepage/static/playground

      - name: Copy playground to homepage static
        run: cp -r dbml-playground/dist dbml-homepage/static/playground

      - name: Check playground
        run: ls -la dbml-homepage/static/playground

      - name: Install homepage dependencies
        working-directory: dbml-homepage
        run: yarn install --frozen-lockfile

      - name: Build homepage
        working-directory: dbml-homepage
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbml-homepage/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
