name: Deploy DBML docs to Github Pages

on: workflow_dispatch

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: dbml-homepage

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          # cache: yarn
          # cache-dependency-path: ./dbml-homepage/yarn.lock

      - name: Check env
        run: |
          node -v
          yarn -v

      - name: Install playground dependencies
        working-directory: dbml-playground
        run: yarn install --frozen-lockfile

      - name: Build playground
        working-directory: dbml-playground
        run: yarn build

      - name: Clean up old playground build
        run: rm -rf static/playground

      - name: Copy playground to homepage static
        run: cp -r ../dbml-playground/dist static/playground

      - name: Install homepage dependencies
        run: yarn install --frozen-lockfile

      - name: Build homepage
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbml-homepage/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
